# Create a pod that reads and writes to the
# NFS server via an NFS volume.
# NFS s erver needs to be created first.
# On GCE, Filestore > CREATE INSTANCE

kind: Pod
apiVersion: v1
metadata:
  name: pod-using-nfs
spec:
  volumes:
    - name: nfs-volume
      nfs: 
        server: 172.30.159.234      # 172.30.159.234:/myvolume
        path: /myvolume
  containers:
    - name: app
      image: alpine
      volumeMounts:
        - name: nfs-volume
          mountPath: /var/nfs
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/nfs/dates.txt; sleep 5; done"]