apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    multi: container
spec:
  containers:
    - name: curler
      image: viejo/curl
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do curl localhost; done;" ]
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80