apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  hostNetwork: true       # this parameter needs to be on true if working with hostPort.
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 80        # this port needs to match containerPort