# In this scenario, files will be create under /etc/foo
# File names will be decoded, so for this case there would be 2 files:
# /etc/foo/username and /etc/foo/password
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: credentials
      defaultMode: 256
      # also can customize the path where to keep the file
      # in this case, instead of creating it under /etc/foo/username,
      # it will be created under /etc/foo/another/path
      items:
      - key: username
        path: another/path
        mode: 511 # 511 decimal = 777 octal