apiVersion: v1
kind: Pod
metadata:
  name: all-in-one-pod
spec:
  containers:
    - name: bb
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: all-in-one
  restartPolicy: Never