apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: alive-n-ready-tcp
spec:
  containers:
  - name: nginx
    image: viejo/nginx-healthz
    command: ["nginx", "-g", "daemon off;"]
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
