# $ kubectl create configmap redis-config --from-file redis-config.yaml
# When creating through command line, there will be a slight difference: The file will appear as redis-config.yaml
#
# https://redis.io/topics/lru-cache
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru