# The variables will be defined in a text file.
# cat /etc/config/keys
# cat /etc/config/types
# cat /etc/config/
apiVersion: v1
kind: Pod
metadata:
  name: cm-as-vol-pod
spec:
  containers:
    - name: bb
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh","-c","sleep 1000" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
        items:
        - key: special.level
          path: keys
        - key: special.type
          path: types
        - key: hello
          path: world
  restartPolicy: Never