apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-pod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bb
            image: busybox
            args:
            - /bin/sh
            - -c
            - date;
          restartPolicy: OnFailure